//Modified by Professor Reed -- Feb. 2nd, 2015
//Now uses subroutines
//
//
//#pragma config(Sensor, S3, color, sensorEV3_Color)
//#pragma config(Sensor, S3,              color,         sensorEV3_Color)
//#pragma config(Motor,  motorB,          leftwheel,     tmotorEV3_Large, PIDControl, reversed, encoder)
//#pragma config(Motor,  motorC,          rightwheel,    tmotorEV3_Large, PIDControl, reversed, encoder)
//
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//
//
//Global variables:
int   nMotorSpeedSetting = 30; //motor speed setting -- inital 30
float nPfactor           = 0.3;//np factor           -- inital 0.3
int   grey               = 50; //grey                -- 50
int   lowest             = 100;//lowest              -- 100
int   highest            = 0;  //highest             -- 0
//
//
//scanLine Routine--->
void   scanLine()
{
  motor[motorB]  = 10;
  motor[motorA] = -10;
  time1[T1]         = 0;
  while(time1[T1] < 500)
  {
    if (SensorValue[S3] > highest)
    {
      highest = SensorValue[S3];
    }
    if (SensorValue[S3] < lowest)
    {
      lowest = SensorValue[S3];
    }
  }
  grey = (highest - lowest) / 2;
  motor[motorB] = 0;
  motor[motorC] = 0;
}// end of scanLine()
//

task main()
{
  float error;

  scanLine(); //call scanLine()!

  while (true)
  {
    error = SensorValue[S3] - grey;
    motor[motorB] = nMotorSpeedSetting - round(error * nPfactor);
    motor[motorC] = nMotorSpeedSetting + round(error * nPfactor);
    wait1Msec(50);
  }
}// end of task main()
//
