//Modified by Professor Reed, Feb. 02, 2015
//A better swing program
//
#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
This program will have your robot make a right swing turn for one (1) second and then make a
left swing turn afterwards. At the end of the program, all motors will shut down automatically
and turn off.

ROBOT CONFIGURATION: LEGO EV3 REM Bot
MOTORS & SENSORS:
[I/O Port]          [Name]              [Type]                			[Location]
MotorC        			leftMotor           LEGO EV3 Motor		      Left side motor
MotorB       				rightMotor          LEGO EV3 Motor		      Right side motor (reversed)
------------------------------------------------------------------------------------------------*/
short int setlftmotorOff()
{
	setMotorSpeed(motorC, 0);			//Set the leftMotor (motor1) to Off
	return (motorC);
}// end of set the left motor

short int setlftmotorspeed()
{
	setMotorSpeed(motorC, 100);			//Set the leftMotor (motor1) to Off
	return (motorC);
}
short int setrhtmotorOff()
{
	setMotorSpeed(motorC, 0);			//Set the leftMotor (motor1) to Off
	return (motorB);
}// end of set the left motor

short int setrhtmotorspeed()
{
	setMotorSpeed(motorB, 100);			//Set the rightMotor (motor1) to Off
	return (motorB);
}

short int waitonesec()
{
	sleep(1000);
	return (1);
}

// main task area begins below:
//
task main()
{

setlftmotorOff();
setlftmotorspeed();
waitonesec();
//
setrhtmotorOff();
setrhtmotorspeed();
waitonesec();
//

}// end of task main()!!!
// Modified by ProfJRR -- Feb. 02, 2015
// end of EV3 Program in ROBOTC to swing around EV3 unit
